name = "Kitchen Sink 1.7.10"
author = "ThePixelbrain"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "428599daa9c7028e1b76effefbdca5432e2db77e63551b56d998ad30fe48d5ff"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
