name = "Kitchen Sink 1.7.10"
author = "ThePixelbrain"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "28dd37c2832dd993c918856d39ae4743cc9d66f85efb6aaed3568b76ca245a00"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
