name = "Kitchen Sink 1.7.10"
author = "ThePixelbrain"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "70bb57122491be116676ab2edda3542edb413f1932ae265957a5d49c07629bb4"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
