name = "Kitchen Sink 1.7.10"
author = "ThePixelbrain"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1bdd6bc28f19662359b476d6fbd5392900897a8f3f9ff8f26ca9691da1e81c81"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
