name = "Kitchen Sink 1.7.10"
author = "ThePixelbrain"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "88f70e6c7cfeffdaba3de271cd290d72a334643a0042250a193d1800f2e84eb0"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
