name = "Kitchen Sink 1.7.10"
author = "ThePixelbrain"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1f03619fc88cde370759303f88110c12e73081f2959d6241ef23ecfe3c6a6a90"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
